### ISSUE TITLE
是否有完整安装教程

### ISSUE THREAD

**Issue by haig233** [Mockingbird1234/skapp#1]
是否有完整安装教程？此项目是否包含web端？

**Comment by Mockingbird1234** [comment]
安装教程目前还没有，近期会补上；web端是另外一个项目，目前没有开源，在线访问地址是：http://sk.ncer.top

**Comment by haig233** [comment]
> 安装教程目前还没有，近期会补上；web端是另外一个项目，目前没有开源，在线访问地址是：http://sk.ncer.top

感谢回复，希望作者能尽快补上教程，感谢
