### ISSUE TITLE
突然间得闭源，让我猝不及防

### ISSUE THREAD

**Issue by BlackTrace** [Mockingbird1234/skapp#13]
最近这几天才在学习您的代码，今天突然在自己的star里面找不到这个项目了，从浏览器历史记录里找到，没想到，就这么突然天翻地覆。

**Comment by Mockingbird1234** [comment]
不好意思哈，谢谢支持这个软件，计划赶不上变化，如果想学习的话，可以到码云搜索skapp，有之前的旧代码，整体架子都差不多。

**Comment by feng99** [comment]
> 学习的话，可以到码云搜索skapp，有之前的

发生了什么呢?  申请加入qq群 也没有人处理
