### ISSUE TITLE
SK2.4.0  bug及功能收集

### ISSUE THREAD

**Issue by Mockingbird1234** [Mockingbird1234/skapp#15]
由于每个人的环境及配置不太一样，本人在开发过程中可能没有顾及那么多点，所以在各自环境中可能会遇到一些意想不到的bug及问题，大家可以把2.4.0版本中遇到的问题写在这条issue下面，我会回复并且在接下来的版本中统一修复bug，尽量不要私聊我了，人一多我也记不住，也可以将自己想新增的功能写在下面，我觉得合适可能就在接下来的版本中加上了。模板如下
```
## BUG

<!--
 1. BUG 描述
 2. 如何复现
 3. APP名字
-->

## 问题

<!-- 使用过程中的疑问 -->

## 功能

<!-- 新增功能建议 -->
```

**Comment by Mockingbird1234** [comment]
## BUG

1.ios下从顶部下拉后，视频的音量图标不消失（未）
2.手机号注册的用户可能发不了问题反馈
3.某些m3u8资源下载不成功，

## 问题



## 功能

**Comment by shoayongchun** [comment]
增加苹果端的下载功能。

**Comment by shoayongchun** [comment]
APP的播放源 排序位置是怎么修改的

**Comment by Mockingbird1234** [comment]
> 1.软件的核心是播放，希望可以进一步优化播放加载速度，解析逻辑。目前会有遇到同一条解析接口同一个视频网页可以播放但是APP一直加载的问题。
> 2.当前播放源播放失败，点击更换播放源后需要在点击一下集数才可以播放， 希望改成切换播放源后直接对当前集数开始加载播放 ，不需要再次点击集数。

1.已经修复，可在下个版本测试下
2.这个问题下个版本也会修改

**Comment by Mockingbird1234** [comment]
> 增加苹果端的下载功能。

由于对原生代码不熟悉，ios端没有找到合适的插件，如果你有合适的flutter  m3u8下载插件，可以联系我。

**Comment by Mockingbird1234** [comment]
> APP的播放源 排序位置是怎么修改的

这个目前是不能排序的，只是根据入库的顺序显示，后面我会考虑增加播放器排序功能。

**Comment by MechanicF** [comment]
新增功能建议
播放界面点击下载 然后查看下载列表后返回 会直接退出播放界面 回到首页
建议优化成 返回到上一级

**Comment by 14895869** [comment]
建议优化一下投屏页面，不止能投屏乐播，应该要支持其他软件，并且支持投屏换集，不需要重新投屏

**Comment by 14895869** [comment]
建议把备注加上底色，因为备注通常为更新到多少集，纯白字体加上图片就会看不清楚

**Comment by 14895869** [comment]
影片详情页面字体可以大一点，目前来说太小了，而且备注希望可以用其他颜色标明，不要跟在名字后面 可以另起一行

**Comment by 14895869** [comment]
1、建议设置一个解析最大时间限制，超过10秒没有解析成功提示失败并且提醒更换线路。
2、影片分类由于苹果cms不统一，所以电视剧和电源经常会分为大陆以及内地两种，但是意思都是一样的，可以添加一个选项合并分类，或者类似于苹果cms一样可以绑定分类。
期待您的回复

**Comment by Mockingbird1234** [comment]
> 新增功能建议
> 播放界面点击下载 然后查看下载列表后返回 会直接退出播放界面 回到首页
> 建议优化成 返回到上一级

好的

**Comment by Mockingbird1234** [comment]
> 影片详情页面字体可以大一点，目前来说太小了，而且备注希望可以用其他颜色标明，不要跟在名字后面 可以另起一行

1.部分字体确实有些小，会增加1-2个字号
2.备注会选用其他颜色，并且另起一行

**Comment by Mockingbird1234** [comment]
> 1、建议设置一个解析最大时间限制，超过10秒没有解析成功提示失败并且提醒更换线路。
> 2、影片分类由于苹果cms不统一，所以电视剧和电源经常会分为大陆以及内地两种，但是意思都是一样的，可以添加一个选项合并分类，或者类似于苹果cms一样可以绑定分类。
> 期待您的回复

1.下个版本增加单个解析时间限制，后台可修改，单个解析如果超过此限制，则切换下一解析。
2.app的影片分类可以在后台设置，不会加合并分类，可以在后台手动添加大陆，内地两个分类。

**Comment by Mockingbird1234** [comment]
> 建议优化一下投屏页面，不止能投屏乐播，应该要支持其他软件，并且支持投屏换集，不需要重新投屏

投屏由于目前没有测试设备，暂时看不了这个问题。

**Comment by Mockingbird1234** [comment]
> 建议把备注加上底色，因为备注通常为更新到多少集，纯白字体加上图片就会看不清楚

好的

**Comment by MechanicF** [comment]
希望后台能适配更多广告联盟

**Comment by MechanicF** [comment]
希望可以设置观看多少次视频强行弹出一次插页式广告

**Comment by mahua123456** [comment]
希望可以设置观看视频激励广告一天弹出几次，搜索能支持繁体搜索！

**Comment by mahua123456** [comment]
json解析每条播放器线路都可以设置，否则不同的m3u8不同的解析口容易解析失败！

**Comment by mahua123456** [comment]
从播放记录点进去播放会从第一集的记忆点开始播放，不会定位到其他集，播放器记忆功能也有点问题！

**Comment by aleikj** [comment]
下载功能经常失败，中断，请优化，谢谢。播放页资源 失败后有一次刷新按钮的机会，刷新后再失败就显示切换播放源。

**Comment by aleikj** [comment]
播放面banner广告可以移到剧集下面

**Comment by aleikj** [comment]
后台用户留言，回复后用户可以看到
