### ISSUE TITLE
关于解析官方视频

### ISSUE THREAD

**Issue by haig233** [Mockingbird1234/skapp#6]
解析官方视频，应该搭配JSON接口来使用，之前看你的代码，都是iframe其他解析接口的网页，这样就会有广告问题
目前，很多套解析系统都支持JSON格式返回播放地址，所以可以直接用本地播放器播放返回的视频源地址
返回格式示例：
```json
{
	"code": "200",
	"success": "1",
	"utype": "m3u8",
	"ptype": "html5",
	"player": "dplayer",
	"url": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
	"data": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
	"name": "jiexi"
}
```

**Comment by Mockingbird1234** [comment]
> 解析官方视频，应该搭配JSON接口来使用，之前看你的代码，都是iframe其他解析接口的网页，这样就会有广告问题
> 目前，很多套解析系统都支持JSON格式返回播放地址，所以可以直接用本地播放器播放返回的视频源地址
> 返回格式示例：
> 
> ```json
> {
> 	"code": "200",
> 	"success": "1",
> 	"utype": "m3u8",
> 	"ptype": "html5",
> 	"player": "dplayer",
> 	"url": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
> 	"data": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
> 	"name": "jiexi"
> }
> ```


感谢你提的issue，由于对这方面了解不多，一直没有找到可以直接返回json格式的API或网站，可以提供一个吗？感谢~~

**Comment by haig233** [comment]
> > 解析官方视频，应该搭配JSON接口来使用，之前看你的代码，都是iframe其他解析接口的网页，这样就会有广告问题
> > 目前，很多套解析系统都支持JSON格式返回播放地址，所以可以直接用本地播放器播放返回的视频源地址
> > 返回格式示例：
> > ```json
> > {
> > 	"code": "200",
> > 	"success": "1",
> > 	"utype": "m3u8",
> > 	"ptype": "html5",
> > 	"player": "dplayer",
> > 	"url": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
> > 	"data": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
> > 	"name": "jiexi"
> > }
> > ```
> 
> 感谢你提的issue，由于对这方面了解不多，一直没有找到可以直接返回json格式的API或网站，可以提供一个吗？感谢~~

已PM

**Comment by huanzhiyi** [comment]
> 解析官方视频，应该搭配JSON接口来使用，之前看你的代码，都是iframe其他解析接口的网页，这样就会有广告问题
> 目前，很多套解析系统都支持JSON格式返回播放地址，所以可以直接用本地播放器播放返回的视频源地址
> 返回格式示例：
> 
> {
> 	"code": "200",
> 	"success": "1",
> 	"utype": "m3u8",
> 	"ptype": "html5",
> 	"player": "dplayer",
> 	"url": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
> 	"data": "https:\/\/pcvideoydott.titan.mgtv.com\/c1\/2020\/10\/31_0\/0F6B9830116A15300BB43A701F72EC5D_20201031_1_1_2615_mp4\/68C1CAAF91DB6129A794ECCF27089C06.m3u8?arange=0&jxname=jianghu&pm=SguqIaP5v9AQrZ0IUpi7OSp2aAt4xsHoEI685Iv60vjFQF6Tj~G1wufh9w2KKZNUVcXBYzwRbn3sF0~7DjdHwzZWgP3P~tiO~xpfUYjZ9Dl7MBtrljsSRxa6dFj5s9iuyGwpv_s8_JxWcBuTcW87dfUcJVJBt2mEp1NqFcr8u75VSzkK8BqTO9t4Ltsa4KIqEPNOTU9qzfFWs1g78UVzePsVGeQRqd7AJl6l9TW0QxP7NSPcX4rncG0Qiv9RV7VSbQzrw0pto08fM5pcl235UQ_zhnz6HWQaB9vmGuZp6JmPw8bv16aRlk6aGr2l8w~h5wd4F70y6OMq2lf_JUJN~_PfxLvKa1p0rw2WfXPDtzVaWqsnWnwHEGIs6TLq3cHqiPN2cy4byTCcQHRmN9L3TLEE8QSNHSI1mhKCJhHU9GTiMWR8j67r6lk49P_bDcG2CsqdB9XVQNzwiZLowDfb_4frEIGQdZHpNtXtbrDbu8m4eT0H&mr=k9bPlpavNt10SxnjXRkyY3tMe_b2xlbxdMmm1EeXO~iL1x5HRJCOuAHOI57cZwxLDtg4fjf1srJv66Jq3aX_UgNY1_tpR_W8NGXLYACJoRmd0JwmdYEYtWxHvQXBwISRo84XG5hY94N1PD2FOyZT~QuKS_TjMiPHwMuBrphmJee_NGUCIwjomaBQM~WPCSYghQoQGXlFLlVLSzyS0CZ64SEJ20o-&uid=9681952cec131090e092c7ac077568f4&vcdn=0&scid=25066",
> 	"name": "jiexi"
> }
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

你好，请问有相关二次解析的解析系统返回json的源码相关链接吗？网上的基本返还的是html
