### ISSUE TITLE
建议优化APP数据获取

### ISSUE THREAD

**Issue by haig233** [Mockingbird1234/skapp#9]
测试环境：
后端：国内VPS，100Mbit带宽，网络为广州移动
苹果cms+数据库：腾讯云国内云服务器，坐标广东广州

APP测试环境网络：广州电信

打开APP，APP内数据获取依旧加载缓慢，部分分类可以实现3s内数据加载完毕，还有部分分类一直卡顿，超过30s依旧没有加载出来

个人认为网络状态已经很好了，有可能是程序代码问题，作者可以私聊我，获取测试过程中的录屏视频

**Comment by Mockingbird1234** [comment]
可以先单独测下api的响应速度，如果api响应慢，那应该就不是app的问题。
